FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish aspnet-core.csproj -c Release -o /app
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
EXPOSE 5101
ENTRYPOINT ["dotnet", "aspnet-core.dll", "--urls", "http://0.0.0.0:5101"]
